---
title: "AALOEB coloured in"
author: "Neil Pettinger"
date: "2025-01-20"
output: html_document
---
### That jagged line diagram but in colour

### Step 0 - install/load packages

```{r}
library(tidyverse)
library(readxl)
#install.packages("magick")
library(magick)
library(ggpattern)
install.packages("ggtext")
library(ggtext)
```

### Step 1 - import the data

```{r}
dataframe_01 <-
  read_xlsx("data/gm_mean_occ_beds.xlsx")
  
```

### Step 2 - add a variable with the bed allocation

```{r}
dataframe_01a <-
  dataframe_01 |> 
  mutate(bed_allocation = 55) |> 
  mutate(lower = if_else(mean_occupied_beds < bed_allocation,
                         mean_occupied_beds,
                         55)) |> 
  mutate(higher = if_else(mean_occupied_beds >= bed_allocation,
                         mean_occupied_beds,
                         55)) |> 
  mutate(diff_lower = lower - bed_allocation) |> 
  mutate(diff_higher = higher - bed_allocation)
```
 
### Step 3 - draw a line graph

```{r}
ggplot(data = dataframe_01a) + 
  geom_line(aes(x = date,
                y = mean_occupied_beds),
            colour = "grey") +
  geom_line(aes(x = date,
                y = bed_allocation)) +
  geom_ribbon(aes(x = date,
                  ymin = lower,
                  ymax = bed_allocation),
              fill = "green",
              alpha = 0.25) +
  geom_ribbon(aes(x = date,
                  ymin = bed_allocation,
                  ymax = higher),
              fill = "red",
              alpha = 0.25) +
  scale_y_continuous(limits = c(50, 70),
                     breaks = seq(50, 70, 2)) +
  labs(title = "Always At Least One Empty Bed",
       subtitle = "Anytown General Hospital | General Medicine | Apr to Sep 2024",
       x = element_blank(),
       y = element_blank()) +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"))
```

Try another type of graph

```{r}
ggplot(data = dataframe_01a)  + 
  geom_ribbon_pattern(aes(x = date, 
                          ymin = bed_allocation,
                          ymax = higher),
                      pattern = "gradient",
                      pattern_fill = "white",
                      pattern_fill2 = "red") +
  geom_ribbon_pattern(aes(x = date, 
                          ymin = bed_allocation,
                          ymax = lower),
                      pattern = "gradient",
                      pattern_fill = "green",
                      pattern_fill2 = "white") +
  geom_line(aes(x = date,
                y = bed_allocation)) +
  scale_y_continuous(limits = c(50, 70),
                     breaks = seq(50, 70, 2)) +
  labs(title = "Always At Least One Empty Bed",
       subtitle = "Anytown General Hospital | General Medicine | Apr to Sep 2024",
       x = element_blank(),
       y = element_blank()) +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"))
```
Let's try it with lines/columns up or down in relation to the mean line

```{r}
green_red_plot <-
  ggplot(data = dataframe_01a) +
 geom_linerange(aes(x = date,
                    ymin = mean_occupied_beds, 
                    ymax = higher),
                colour = "#00FF00",
                linewidth = 0.5) +
  geom_linerange(aes(x = date,
                    ymin = lower, 
                    ymax = mean_occupied_beds),
                 colour = "#FF0000",
                 linewidth = 0.5) +
  geom_line(aes(x = date,
                y = bed_allocation)) +
  scale_y_continuous(limits = c(50, 70),
                     breaks = seq(50, 70, 5)) +
  labs(title = "<span style='color:#FF0000'>Bed overflow</span> happens more often than
    <span style='color:#00FF00'>bed underflow</span>",
       subtitle = "Anytown General Hospital | General Medicine (55 beds) | 1 Apr 2024 to 8 Sep 2024",
       x = element_blank(),
       y = element_blank()) +
  theme(panel.grid = element_blank(),
        panel.background = element_rect(fill = "white"),
        plot.title = ggtext::element_markdown())
```

save that plot

```{r}
ggsave(green_red_plot, 
       filename = "green_red_plot.png",
       height = 9, width = 16, units = "cm")
```

